import * as fs from 'node:fs/promises';
import * as path from 'node:path';

export async function runMigrations(projectDir: string) {
  const lockfilePath = path.join(projectDir, 'sfg.lock.json');
  try {
    const lockfile = JSON.parse(await fs.readFile(lockfilePath, 'utf-8'));
    console.log(`[Migration] Found project generated by scaffold-forge v${lockfile.generator.version}`);
    console.log(`[Migration] Config Hash: ${lockfile.configHash}`);
    console.log('[Migration] Checking for schema updates...');
    console.log('[Migration] No pending migrations. Project is up to date.');
  } catch (err) {
    console.log('[Migration] No sfg.lock.json found or invalid format. Skipping migrations.');
  }
}