name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # Perintah ini akan dijalankan oleh Changesets Action
          publish: npm run release
        env:
          # Token ini digunakan oleh Changesets untuk membuat PR dan Tag di GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Token ini digunakan oleh NPM untuk mem-publish paket ke registry
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
